server:
  port: 8080

spring:
  application:
    name: agriculture

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    default-schema: migrations
    liquibase-schema: migrations
    database-change-log-table: databasechangelog
    database-change-log-lock-table: databasechangeloglock
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: agriculture