services:
  cinerate_postgres:
    image: "postgres:16"
    container_name: cinerate_postgres
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/var/lib/postgresql/data:rw
      - ./create_migrations_schema.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  postgres_data: